# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 240, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 430, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 20, 131, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_add_blacklist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_blacklist.setGeometry(QtCore.QRect(260, 280, 31, 31))
        self.pushButton_add_blacklist.setObjectName("pushButton_add_blacklist")
        self.pushButton_remove_blacklist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove_blacklist.setGeometry(QtCore.QRect(260, 340, 31, 31))
        self.pushButton_remove_blacklist.setObjectName("pushButton_remove_blacklist")
        self.pushButton_remove_whitelist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove_whitelist.setGeometry(QtCore.QRect(260, 540, 31, 31))
        self.pushButton_remove_whitelist.setObjectName("pushButton_remove_whitelist")
        self.pushButton_add_whitelist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_whitelist.setGeometry(QtCore.QRect(260, 480, 31, 31))
        self.pushButton_add_whitelist.setObjectName("pushButton_add_whitelist")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(380, 610, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_apply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_apply.setGeometry(QtCore.QRect(240, 610, 75, 23))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.treeWidget_packs = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget_packs.setGeometry(QtCore.QRect(10, 40, 256, 192))
        self.treeWidget_packs.setObjectName("treeWidget_packs")
        self.treeWidget_packs.headerItem().setText(0, "1")
        self.listWidget_blacklist = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_blacklist.setGeometry(QtCore.QRect(10, 260, 231, 151))
        self.listWidget_blacklist.setObjectName("listWidget_blacklist")
        self.listWidget_whitelist = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_whitelist.setGeometry(QtCore.QRect(10, 450, 231, 151))
        self.listWidget_whitelist.setObjectName("listWidget_whitelist")
        self.listWidget_merged = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_merged.setGeometry(QtCore.QRect(310, 40, 256, 561))
        self.listWidget_merged.setObjectName("listWidget_merged")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Blacklist Packs"))
        self.label_2.setText(_translate("MainWindow", "Custom Domain Blacklist"))
        self.label_3.setText(_translate("MainWindow", "Custom Domain Whitelist"))
        self.label_4.setText(_translate("MainWindow", "Complete Merged Blacklist"))
        self.pushButton_add_blacklist.setText(_translate("MainWindow", "+"))
        self.pushButton_remove_blacklist.setText(_translate("MainWindow", "-"))
        self.pushButton_remove_whitelist.setText(_translate("MainWindow", "-"))
        self.pushButton_add_whitelist.setText(_translate("MainWindow", "+"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
